version: 2
updates:
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - rxsto
  assignees:
    - rxsto
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - rxsto
  assignees:
    - rxsto
  commit-message:
    prefix: chore
    include: scope
